envVars:
  - key: PYTHON_VERSION
    value: 3.13.11

  - key: ENVIRONMENT
    value: production

  - key: PORT
    value: PORT

  - key: DB_URL
    fromDatabase:
      name: mydb
      property: connectionString


